//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPolizasQualitas.ServiceQualitasProd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceQualitasProd.entradaSoap")]
    public interface entradaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaImpresion", ReplyAction="*")]
        NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponse RecuperaImpresion(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaImpresion", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponse> RecuperaImpresionAsync(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaImpresionPrueba", ReplyAction="*")]
        NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponse RecuperaImpresionPrueba(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaImpresionPrueba", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponse> RecuperaImpresionPruebaAsync(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaImpresionM15", ReplyAction="*")]
        NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Response RecuperaImpresionM15(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaImpresionM15", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Response> RecuperaImpresionM15Async(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaImpresionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaImpresion", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequestBody Body;
        
        public RecuperaImpresionRequest() {
        }
        
        public RecuperaImpresionRequest(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaImpresionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URLPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URLRecibo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string URLTextos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Inciso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ImpPol;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ImpRec;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int ImpAnexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Ramo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string formaPol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string formaRec;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string formaAnexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Endoso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NoNegocio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Agente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Password;
        
        public RecuperaImpresionRequestBody() {
        }
        
        public RecuperaImpresionRequestBody(
                    string nPoliza, 
                    string URLPoliza, 
                    string URLRecibo, 
                    string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            this.nPoliza = nPoliza;
            this.URLPoliza = URLPoliza;
            this.URLRecibo = URLRecibo;
            this.URLTextos = URLTextos;
            this.Inciso = Inciso;
            this.ImpPol = ImpPol;
            this.ImpRec = ImpRec;
            this.ImpAnexo = ImpAnexo;
            this.Ramo = Ramo;
            this.formaPol = formaPol;
            this.formaRec = formaRec;
            this.formaAnexo = formaAnexo;
            this.Endoso = Endoso;
            this.NoNegocio = NoNegocio;
            this.Agente = Agente;
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaImpresionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaImpresionResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponseBody Body;
        
        public RecuperaImpresionResponse() {
        }
        
        public RecuperaImpresionResponse(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaImpresionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecuperaImpresionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URLPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URLRecibo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string URLTextos;
        
        public RecuperaImpresionResponseBody() {
        }
        
        public RecuperaImpresionResponseBody(string RecuperaImpresionResult, string URLPoliza, string URLRecibo, string URLTextos) {
            this.RecuperaImpresionResult = RecuperaImpresionResult;
            this.URLPoliza = URLPoliza;
            this.URLRecibo = URLRecibo;
            this.URLTextos = URLTextos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaImpresionPruebaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaImpresionPrueba", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequestBody Body;
        
        public RecuperaImpresionPruebaRequest() {
        }
        
        public RecuperaImpresionPruebaRequest(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaImpresionPruebaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URLPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URLRecibo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string URLTextos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Inciso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ImpPol;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ImpRec;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int ImpAnexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Ramo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string formaPol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string formaRec;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string formaAnexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Endoso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NoNegocio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Agente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Password;
        
        public RecuperaImpresionPruebaRequestBody() {
        }
        
        public RecuperaImpresionPruebaRequestBody(
                    string nPoliza, 
                    string URLPoliza, 
                    string URLRecibo, 
                    string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            this.nPoliza = nPoliza;
            this.URLPoliza = URLPoliza;
            this.URLRecibo = URLRecibo;
            this.URLTextos = URLTextos;
            this.Inciso = Inciso;
            this.ImpPol = ImpPol;
            this.ImpRec = ImpRec;
            this.ImpAnexo = ImpAnexo;
            this.Ramo = Ramo;
            this.formaPol = formaPol;
            this.formaRec = formaRec;
            this.formaAnexo = formaAnexo;
            this.Endoso = Endoso;
            this.NoNegocio = NoNegocio;
            this.Agente = Agente;
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaImpresionPruebaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaImpresionPruebaResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponseBody Body;
        
        public RecuperaImpresionPruebaResponse() {
        }
        
        public RecuperaImpresionPruebaResponse(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaImpresionPruebaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecuperaImpresionPruebaResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URLPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URLRecibo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string URLTextos;
        
        public RecuperaImpresionPruebaResponseBody() {
        }
        
        public RecuperaImpresionPruebaResponseBody(string RecuperaImpresionPruebaResult, string URLPoliza, string URLRecibo, string URLTextos) {
            this.RecuperaImpresionPruebaResult = RecuperaImpresionPruebaResult;
            this.URLPoliza = URLPoliza;
            this.URLRecibo = URLRecibo;
            this.URLTextos = URLTextos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaImpresionM15Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaImpresionM15", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15RequestBody Body;
        
        public RecuperaImpresionM15Request() {
        }
        
        public RecuperaImpresionM15Request(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaImpresionM15RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URLPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URLRecibo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string URLTextos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Inciso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ImpPol;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ImpRec;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int ImpAnexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Ramo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string formaPol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string formaRec;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string formaAnexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Endoso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NoNegocio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Agente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Password;
        
        public RecuperaImpresionM15RequestBody() {
        }
        
        public RecuperaImpresionM15RequestBody(
                    string nPoliza, 
                    string URLPoliza, 
                    string URLRecibo, 
                    string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            this.nPoliza = nPoliza;
            this.URLPoliza = URLPoliza;
            this.URLRecibo = URLRecibo;
            this.URLTextos = URLTextos;
            this.Inciso = Inciso;
            this.ImpPol = ImpPol;
            this.ImpRec = ImpRec;
            this.ImpAnexo = ImpAnexo;
            this.Ramo = Ramo;
            this.formaPol = formaPol;
            this.formaRec = formaRec;
            this.formaAnexo = formaAnexo;
            this.Endoso = Endoso;
            this.NoNegocio = NoNegocio;
            this.Agente = Agente;
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaImpresionM15Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaImpresionM15Response", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15ResponseBody Body;
        
        public RecuperaImpresionM15Response() {
        }
        
        public RecuperaImpresionM15Response(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaImpresionM15ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecuperaImpresionM15Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URLPoliza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URLRecibo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string URLTextos;
        
        public RecuperaImpresionM15ResponseBody() {
        }
        
        public RecuperaImpresionM15ResponseBody(string RecuperaImpresionM15Result, string URLPoliza, string URLRecibo, string URLTextos) {
            this.RecuperaImpresionM15Result = RecuperaImpresionM15Result;
            this.URLPoliza = URLPoliza;
            this.URLRecibo = URLRecibo;
            this.URLTextos = URLTextos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface entradaSoapChannel : NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class entradaSoapClient : System.ServiceModel.ClientBase<NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap>, NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap {
        
        public entradaSoapClient() {
        }
        
        public entradaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public entradaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public entradaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public entradaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponse NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap.RecuperaImpresion(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest request) {
            return base.Channel.RecuperaImpresion(request);
        }
        
        public string RecuperaImpresion(
                    string nPoliza, 
                    ref string URLPoliza, 
                    ref string URLRecibo, 
                    ref string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest inValue = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest();
            inValue.Body = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequestBody();
            inValue.Body.nPoliza = nPoliza;
            inValue.Body.URLPoliza = URLPoliza;
            inValue.Body.URLRecibo = URLRecibo;
            inValue.Body.URLTextos = URLTextos;
            inValue.Body.Inciso = Inciso;
            inValue.Body.ImpPol = ImpPol;
            inValue.Body.ImpRec = ImpRec;
            inValue.Body.ImpAnexo = ImpAnexo;
            inValue.Body.Ramo = Ramo;
            inValue.Body.formaPol = formaPol;
            inValue.Body.formaRec = formaRec;
            inValue.Body.formaAnexo = formaAnexo;
            inValue.Body.Endoso = Endoso;
            inValue.Body.NoNegocio = NoNegocio;
            inValue.Body.Agente = Agente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponse retVal = ((NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap)(this)).RecuperaImpresion(inValue);
            URLPoliza = retVal.Body.URLPoliza;
            URLRecibo = retVal.Body.URLRecibo;
            URLTextos = retVal.Body.URLTextos;
            return retVal.Body.RecuperaImpresionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponse> NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap.RecuperaImpresionAsync(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest request) {
            return base.Channel.RecuperaImpresionAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionResponse> RecuperaImpresionAsync(
                    string nPoliza, 
                    string URLPoliza, 
                    string URLRecibo, 
                    string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest inValue = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequest();
            inValue.Body = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionRequestBody();
            inValue.Body.nPoliza = nPoliza;
            inValue.Body.URLPoliza = URLPoliza;
            inValue.Body.URLRecibo = URLRecibo;
            inValue.Body.URLTextos = URLTextos;
            inValue.Body.Inciso = Inciso;
            inValue.Body.ImpPol = ImpPol;
            inValue.Body.ImpRec = ImpRec;
            inValue.Body.ImpAnexo = ImpAnexo;
            inValue.Body.Ramo = Ramo;
            inValue.Body.formaPol = formaPol;
            inValue.Body.formaRec = formaRec;
            inValue.Body.formaAnexo = formaAnexo;
            inValue.Body.Endoso = Endoso;
            inValue.Body.NoNegocio = NoNegocio;
            inValue.Body.Agente = Agente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            return ((NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap)(this)).RecuperaImpresionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponse NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap.RecuperaImpresionPrueba(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest request) {
            return base.Channel.RecuperaImpresionPrueba(request);
        }
        
        public string RecuperaImpresionPrueba(
                    string nPoliza, 
                    ref string URLPoliza, 
                    ref string URLRecibo, 
                    ref string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest inValue = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest();
            inValue.Body = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequestBody();
            inValue.Body.nPoliza = nPoliza;
            inValue.Body.URLPoliza = URLPoliza;
            inValue.Body.URLRecibo = URLRecibo;
            inValue.Body.URLTextos = URLTextos;
            inValue.Body.Inciso = Inciso;
            inValue.Body.ImpPol = ImpPol;
            inValue.Body.ImpRec = ImpRec;
            inValue.Body.ImpAnexo = ImpAnexo;
            inValue.Body.Ramo = Ramo;
            inValue.Body.formaPol = formaPol;
            inValue.Body.formaRec = formaRec;
            inValue.Body.formaAnexo = formaAnexo;
            inValue.Body.Endoso = Endoso;
            inValue.Body.NoNegocio = NoNegocio;
            inValue.Body.Agente = Agente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponse retVal = ((NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap)(this)).RecuperaImpresionPrueba(inValue);
            URLPoliza = retVal.Body.URLPoliza;
            URLRecibo = retVal.Body.URLRecibo;
            URLTextos = retVal.Body.URLTextos;
            return retVal.Body.RecuperaImpresionPruebaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponse> NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap.RecuperaImpresionPruebaAsync(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest request) {
            return base.Channel.RecuperaImpresionPruebaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaResponse> RecuperaImpresionPruebaAsync(
                    string nPoliza, 
                    string URLPoliza, 
                    string URLRecibo, 
                    string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest inValue = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequest();
            inValue.Body = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionPruebaRequestBody();
            inValue.Body.nPoliza = nPoliza;
            inValue.Body.URLPoliza = URLPoliza;
            inValue.Body.URLRecibo = URLRecibo;
            inValue.Body.URLTextos = URLTextos;
            inValue.Body.Inciso = Inciso;
            inValue.Body.ImpPol = ImpPol;
            inValue.Body.ImpRec = ImpRec;
            inValue.Body.ImpAnexo = ImpAnexo;
            inValue.Body.Ramo = Ramo;
            inValue.Body.formaPol = formaPol;
            inValue.Body.formaRec = formaRec;
            inValue.Body.formaAnexo = formaAnexo;
            inValue.Body.Endoso = Endoso;
            inValue.Body.NoNegocio = NoNegocio;
            inValue.Body.Agente = Agente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            return ((NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap)(this)).RecuperaImpresionPruebaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Response NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap.RecuperaImpresionM15(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request request) {
            return base.Channel.RecuperaImpresionM15(request);
        }
        
        public string RecuperaImpresionM15(
                    string nPoliza, 
                    ref string URLPoliza, 
                    ref string URLRecibo, 
                    ref string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request inValue = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request();
            inValue.Body = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15RequestBody();
            inValue.Body.nPoliza = nPoliza;
            inValue.Body.URLPoliza = URLPoliza;
            inValue.Body.URLRecibo = URLRecibo;
            inValue.Body.URLTextos = URLTextos;
            inValue.Body.Inciso = Inciso;
            inValue.Body.ImpPol = ImpPol;
            inValue.Body.ImpRec = ImpRec;
            inValue.Body.ImpAnexo = ImpAnexo;
            inValue.Body.Ramo = Ramo;
            inValue.Body.formaPol = formaPol;
            inValue.Body.formaRec = formaRec;
            inValue.Body.formaAnexo = formaAnexo;
            inValue.Body.Endoso = Endoso;
            inValue.Body.NoNegocio = NoNegocio;
            inValue.Body.Agente = Agente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Response retVal = ((NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap)(this)).RecuperaImpresionM15(inValue);
            URLPoliza = retVal.Body.URLPoliza;
            URLRecibo = retVal.Body.URLRecibo;
            URLTextos = retVal.Body.URLTextos;
            return retVal.Body.RecuperaImpresionM15Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Response> NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap.RecuperaImpresionM15Async(NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request request) {
            return base.Channel.RecuperaImpresionM15Async(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Response> RecuperaImpresionM15Async(
                    string nPoliza, 
                    string URLPoliza, 
                    string URLRecibo, 
                    string URLTextos, 
                    int Inciso, 
                    int ImpPol, 
                    int ImpRec, 
                    int ImpAnexo, 
                    string Ramo, 
                    string formaPol, 
                    string formaRec, 
                    string formaAnexo, 
                    string Endoso, 
                    string NoNegocio, 
                    string Agente, 
                    string Usuario, 
                    string Password) {
            NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request inValue = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15Request();
            inValue.Body = new NavistarPolizasQualitas.ServiceQualitasProd.RecuperaImpresionM15RequestBody();
            inValue.Body.nPoliza = nPoliza;
            inValue.Body.URLPoliza = URLPoliza;
            inValue.Body.URLRecibo = URLRecibo;
            inValue.Body.URLTextos = URLTextos;
            inValue.Body.Inciso = Inciso;
            inValue.Body.ImpPol = ImpPol;
            inValue.Body.ImpRec = ImpRec;
            inValue.Body.ImpAnexo = ImpAnexo;
            inValue.Body.Ramo = Ramo;
            inValue.Body.formaPol = formaPol;
            inValue.Body.formaRec = formaRec;
            inValue.Body.formaAnexo = formaAnexo;
            inValue.Body.Endoso = Endoso;
            inValue.Body.NoNegocio = NoNegocio;
            inValue.Body.Agente = Agente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            return ((NavistarPolizasQualitas.ServiceQualitasProd.entradaSoap)(this)).RecuperaImpresionM15Async(inValue);
        }
    }
}
