//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public short eArea { get; set; }
        public short eAreaPadre { get; set; }
        public byte eTipoArea { get; set; }
        public byte eOrden { get; set; }
        public string vDsccArea { get; set; }
        public string vDscArea { get; set; }
        public byte eEstatus { get; set; }
        public System.DateTime fAlta { get; set; }
        public System.DateTime fModifica { get; set; }
        public string vUsuarioAlta { get; set; }
        public string vUsuarioModifica { get; set; }
    }
}
