//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Models
    {
        public int Model_Id { get; set; }
        public int Family_Id { get; set; }
        public string Model_Description { get; set; }
        public double Model_Price { get; set; }
        public double Model_Factor { get; set; }
        public bool Is_Active { get; set; }
        public string Model_Image { get; set; }
        public Nullable<double> Model_CAT { get; set; }
    
        public virtual cat_Families cat_Families { get; set; }
    }
}
