//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Interest_Rent
    {
        public int Interest_Rent_Id { get; set; }
        public int Interest_Rent_Term { get; set; }
        public double Interest_Rent_Value { get; set; }
    }
}
