//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Mail_Config
    {
        public int Mail_Config_Id { get; set; }
        public int Mail_Config_Port { get; set; }
        public string Mail_Config_Host { get; set; }
        public int Mail_Config_Timeout { get; set; }
        public string Mail_Config_Username { get; set; }
        public string Mail_Config_Password { get; set; }
    }
}
