//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_WebAdministrators
    {
        public int WebAdministratorId { get; set; }
        public string WebAdministratorUsername { get; set; }
        public byte[] WebAdministratorPassword { get; set; }
        public string WebAdministratorName { get; set; }
        public Nullable<int> WebAdministratorRole { get; set; }
    
        public virtual WebAdministratorRole WebAdministratorRole1 { get; set; }
    }
}
