//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes_adicional
    {
        public long cveCliente { get; set; }
        public Nullable<int> id_pregunta { get; set; }
        public string respuesta { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
