//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int cveCliente { get; set; }
        public string nombre { get; set; }
        public string pass { get; set; }
        public byte status { get; set; }
        public string rfc { get; set; }
        public string email { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public string codigoPostal { get; set; }
        public string poblacion { get; set; }
        public string estado { get; set; }
        public bool remindMe { get; set; }
    }
}
