//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class contenido
    {
        public long id_contenido { get; set; }
        public string detalle { get; set; }
        public string contenido1 { get; set; }
        public string pagina { get; set; }
        public Nullable<int> orden { get; set; }
        public string url { get; set; }
        public string tipo { get; set; }
    }
}
