//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cPersona
    {
        public int PNA_FL_PERSONA { get; set; }
        public string PNA_CL_RFC { get; set; }
        public string PNA_DS_NOMBRE { get; set; }
        public string PNA_DS_EMAIL { get; set; }
        public byte PNA_FG_STATUS { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string Telcelular { get; set; }
        public string TelFijo { get; set; }
    }
}
