//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTRL_BITACORA_GRAL
    {
        public decimal CONS { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ACCION { get; set; }
        public Nullable<int> PNA_FL_PERSONA { get; set; }
        public string CTO_FL_CVE { get; set; }
    }
}
