//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kcontrato
    {
        public string CTO_FL_CVE { get; set; }
        public int PNA_FL_PERSONA { get; set; }
        public string TOP_CL_CVE { get; set; }
        public byte EMP_FL_CVE { get; set; }
        public byte CTO_CL_MONEDA { get; set; }
        public byte CTO_FG_STATUS { get; set; }
    }
}
