//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientos_190814
    {
        public long id_movimiento { get; set; }
        public string cveCliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string banco { get; set; }
        public Nullable<double> cantidad { get; set; }
    }
}
