//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sfiinternationalEntities : DbContext
    {
        public sfiinternationalEntities()
            : base("name=sfiinternationalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_Families> cat_Families { get; set; }
        public virtual DbSet<cat_Informative_PDF> cat_Informative_PDF { get; set; }
        public virtual DbSet<cat_Interest_Financial_Leasing> cat_Interest_Financial_Leasing { get; set; }
        public virtual DbSet<cat_Interest_Rent> cat_Interest_Rent { get; set; }
        public virtual DbSet<cat_Interest_Simple_Credit> cat_Interest_Simple_Credit { get; set; }
        public virtual DbSet<cat_Mail_Config> cat_Mail_Config { get; set; }
        public virtual DbSet<cat_Models> cat_Models { get; set; }
        public virtual DbSet<cat_Slider_Text> cat_Slider_Text { get; set; }
        public virtual DbSet<cat_Step_Section> cat_Step_Section { get; set; }
        public virtual DbSet<cat_Web_Snippets> cat_Web_Snippets { get; set; }
        public virtual DbSet<cat_WebAdministrators> cat_WebAdministrators { get; set; }
        public virtual DbSet<info_CAT> info_CAT { get; set; }
        public virtual DbSet<WebAdministratorRole> WebAdministratorRoles { get; set; }
        public virtual DbSet<campania> campanias { get; set; }
        public virtual DbSet<Solicitudes_PaperLess> Solicitudes_PaperLess { get; set; }
        public virtual DbSet<aclaracionStatu> aclaracionStatus { get; set; }
        public virtual DbSet<Bases_Historicas> Bases_Historicas { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<clientes_adicional> clientes_adicional { get; set; }
        public virtual DbSet<Confirmacion> Confirmacions { get; set; }
        public virtual DbSet<contenido> contenidos { get; set; }
        public virtual DbSet<CTRL_BITACORA_GRAL> CTRL_BITACORA_GRAL { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
        public virtual DbSet<faq> faqs { get; set; }
        public virtual DbSet<movimiento> movimientos { get; set; }
        public virtual DbSet<movimientos_190814> movimientos_190814 { get; set; }
        public virtual DbSet<operadore> operadores { get; set; }
        public virtual DbSet<pagosBanamex> pagosBanamexes { get; set; }
        public virtual DbSet<pagosBanamex_190814> pagosBanamex_190814 { get; set; }
        public virtual DbSet<pagosHSBC> pagosHSBCs { get; set; }
        public virtual DbSet<parametro> parametros { get; set; }
        public virtual DbSet<pregunta> preguntas { get; set; }
        public virtual DbSet<Reporte> Reportes { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<kcontrato> kcontratoes { get; set; }
        public virtual DbSet<TContrato> TContratoes { get; set; }
        public virtual DbSet<Tipo_Operacion_Area> Tipo_Operacion_Area { get; set; }
        public virtual DbSet<TTarjeta> TTarjetas { get; set; }
        public virtual DbSet<vw_Menu_Has_Submenu> vw_Menu_Has_Submenu { get; set; }
        public virtual DbSet<vw_Submenus> vw_Submenus { get; set; }
        public virtual DbSet<cPersona> cPersonas { get; set; }
    }
}
