//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class operadore
    {
        public int id_oper { get; set; }
        public string operador { get; set; }
        public string pass { get; set; }
        public Nullable<int> activo { get; set; }
        public string nombre { get; set; }
    }
}
