//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagosHSBC
    {
        public long id_pago { get; set; }
        public Nullable<long> id_movimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cveCliente { get; set; }
        public string Operacion { get; set; }
        public string StatusBital { get; set; }
        public string MensajeBital { get; set; }
        public string FolioBital { get; set; }
        public string FRef1 { get; set; }
        public string FRef2 { get; set; }
        public string FRef3 { get; set; }
        public string URLrespuesta { get; set; }
        public string FImporte { get; set; }
        public string tccmcend { get; set; }
    }
}
