//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public long id_reporte { get; set; }
        public string id_usuario { get; set; }
        public Nullable<long> id_servicio { get; set; }
        public Nullable<long> id_subservicio { get; set; }
        public Nullable<long> id_cliente { get; set; }
        public string id_contrato { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> f_alta { get; set; }
        public Nullable<long> id_status { get; set; }
        public Nullable<System.DateTime> f_compromiso { get; set; }
        public string archivos { get; set; }
        public Nullable<System.DateTime> f_cierre { get; set; }
        public string comentarioCierre { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string campo9 { get; set; }
    }
}
