//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public long id_servicio { get; set; }
        public string Servicio1 { get; set; }
        public string activo { get; set; }
        public Nullable<int> correo { get; set; }
        public Nullable<double> dias { get; set; }
        public Nullable<long> id_padre { get; set; }
        public string Servicio_Internet { get; set; }
    }
}
