//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes_PaperLess
    {
        public int eSolicitud { get; set; }
        public int eCliente { get; set; }
        public string vCorreo { get; set; }
        public System.DateTime fAlta { get; set; }
        public System.DateTime fActualiza { get; set; }
        public byte eEstatus { get; set; }
        public int BIT_FL_CVE { get; set; }
        public int eGestion { get; set; }
    }
}
