//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public long id_status { get; set; }
        public string status1 { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public string color { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> correo { get; set; }
        public string Status_Internet { get; set; }
    }
}
