//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TContrato
    {
        public int IdContrato { get; set; }
        public string Contrato { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdTipoCredito { get; set; }
        public Nullable<int> IdEstatusContrato { get; set; }
        public Nullable<decimal> Capital { get; set; }
        public Nullable<decimal> PorcEnganche { get; set; }
        public Nullable<decimal> Enganche { get; set; }
        public Nullable<decimal> CapitalFinanciado { get; set; }
        public int IdPeriodicidad { get; set; }
        public Nullable<int> Plazo { get; set; }
        public int IdMoneda { get; set; }
        public Nullable<System.DateTime> FecInicioContrato { get; set; }
        public Nullable<System.DateTime> FecPrimeraRenta { get; set; }
        public Nullable<System.DateTime> FecActivacion { get; set; }
        public Nullable<System.DateTime> FecFinContrato { get; set; }
        public int IdTasa { get; set; }
        public Nullable<decimal> TasaBase { get; set; }
        public Nullable<decimal> PuntosMas { get; set; }
        public Nullable<decimal> PuntosPor { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public Nullable<decimal> TasaBaseMora { get; set; }
        public int IdTasaMora { get; set; }
        public Nullable<decimal> PuntosMasMora { get; set; }
        public Nullable<decimal> PuntosPorMora { get; set; }
        public Nullable<decimal> FactorMora { get; set; }
        public Nullable<decimal> TasaMora { get; set; }
        public Nullable<decimal> SaldoInsoluto { get; set; }
        public Nullable<decimal> BallonPayment { get; set; }
        public Nullable<decimal> PorcBallonPayment { get; set; }
        public Nullable<decimal> ValorResidual { get; set; }
        public Nullable<decimal> PorcValorResidual { get; set; }
        public Nullable<decimal> DepositoEnGarantia { get; set; }
        public Nullable<decimal> PorcDepositoEnGarantia { get; set; }
        public Nullable<decimal> OpcionDeCompra { get; set; }
        public Nullable<decimal> PorcOpcionDeCompra { get; set; }
        public Nullable<decimal> TasaIva { get; set; }
        public Nullable<int> VersionTabla { get; set; }
        public Nullable<int> IdTipoCalculoTasaVariable { get; set; }
        public Nullable<int> DiaCorteDisposiciones { get; set; }
        public Nullable<int> DiaPagoDisposiciones { get; set; }
        public Nullable<int> IdPersonaTitular { get; set; }
        public Nullable<int> IdPersonaRepresentante { get; set; }
        public Nullable<decimal> CAT { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
    }
}
