//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTarjeta
    {
        public int IdTarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public string NIP { get; set; }
        public string Vigencia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public int IdTipoEntregaTarjeta { get; set; }
        public Nullable<bool> CartaBienvenida { get; set; }
        public string NombreImpresion { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdTipoRelacion { get; set; }
        public Nullable<int> IdEstatusTarjeta { get; set; }
        public string MotivoCancelacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
    }
}
