//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Submenus
    {
        public int Submenu_Id { get; set; }
        public string Submenu_Name { get; set; }
        public string Submenu_Name_English { get; set; }
        public int Submenu_Order { get; set; }
        public string Menu_Link { get; set; }
        public string Menu_Name { get; set; }
        public bool Is_Active { get; set; }
        public string Submenu_PDF_Folder { get; set; }
    }
}
