//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavistarPagos.EstadoCuentaWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ClaveErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ArchivoPDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NavistarPagos.EstadoCuentaWs.ArrayOfString Filepdf64Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClaveError {
            get {
                return this.ClaveErrorField;
            }
            set {
                if ((this.ClaveErrorField.Equals(value) != true)) {
                    this.ClaveErrorField = value;
                    this.RaisePropertyChanged("ClaveError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string JSON {
            get {
                return this.JSONField;
            }
            set {
                if ((object.ReferenceEquals(this.JSONField, value) != true)) {
                    this.JSONField = value;
                    this.RaisePropertyChanged("JSON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] ArchivoPDF {
            get {
                return this.ArchivoPDFField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoPDFField, value) != true)) {
                    this.ArchivoPDFField = value;
                    this.RaisePropertyChanged("ArchivoPDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public NavistarPagos.EstadoCuentaWs.ArrayOfString Filepdf64 {
            get {
                return this.Filepdf64Field;
            }
            set {
                if ((object.ReferenceEquals(this.Filepdf64Field, value) != true)) {
                    this.Filepdf64Field = value;
                    this.RaisePropertyChanged("Filepdf64");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadoCuentaWs.WSEstadosDeCuentaSoap")]
    public interface WSEstadosDeCuentaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuentaNavistarPagos", ReplyAction="*")]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponse ObtenEstadoDeCuentaNavistarPagos(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuentaNavistarPagos", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponse> ObtenEstadoDeCuentaNavistarPagosAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuenta", ReplyAction="*")]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponse ObtenEstadoDeCuenta(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponse> ObtenEstadoDeCuentaAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEstadoDeCuenta", ReplyAction="*")]
        NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponse EnviaEstadoDeCuenta(NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEstadoDeCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponse> EnviaEstadoDeCuentaAsync(NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuentaInterno", ReplyAction="*")]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponse ObtenEstadoDeCuentaInterno(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuentaInterno", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponse> ObtenEstadoDeCuentaInternoAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuentaInternoNavistarPagos", ReplyAction="*")]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponse ObtenEstadoDeCuentaInternoNavistarPagos(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenEstadoDeCuentaInternoNavistarPagos", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponse> ObtenEstadoDeCuentaInternoNavistarPagosAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnvioEstadoDeCuentaInterno", ReplyAction="*")]
        NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponse EnvioEstadoDeCuentaInterno(NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnvioEstadoDeCuentaInterno", ReplyAction="*")]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponse> EnvioEstadoDeCuentaInternoAsync(NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaNavistarPagosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuentaNavistarPagos", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequestBody Body;
        
        public ObtenEstadoDeCuentaNavistarPagosRequest() {
        }
        
        public ObtenEstadoDeCuentaNavistarPagosRequest(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaNavistarPagosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int claveEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fechaInicioMovimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fechaFinalMovimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fechaInicioVencimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fechaFinalVencimientos;
        
        public ObtenEstadoDeCuentaNavistarPagosRequestBody() {
        }
        
        public ObtenEstadoDeCuentaNavistarPagosRequestBody(string usuario, string clave, int claveEmpresa, string contrato, string fechaInicioMovimientos, string fechaFinalMovimientos, string fechaInicioVencimientos, string fechaFinalVencimientos) {
            this.usuario = usuario;
            this.clave = clave;
            this.claveEmpresa = claveEmpresa;
            this.contrato = contrato;
            this.fechaInicioMovimientos = fechaInicioMovimientos;
            this.fechaFinalMovimientos = fechaFinalMovimientos;
            this.fechaInicioVencimientos = fechaInicioVencimientos;
            this.fechaFinalVencimientos = fechaFinalVencimientos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaNavistarPagosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuentaNavistarPagosResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponseBody Body;
        
        public ObtenEstadoDeCuentaNavistarPagosResponse() {
        }
        
        public ObtenEstadoDeCuentaNavistarPagosResponse(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaNavistarPagosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavistarPagos.EstadoCuentaWs.ArrayOfString ObtenEstadoDeCuentaNavistarPagosResult;
        
        public ObtenEstadoDeCuentaNavistarPagosResponseBody() {
        }
        
        public ObtenEstadoDeCuentaNavistarPagosResponseBody(NavistarPagos.EstadoCuentaWs.ArrayOfString ObtenEstadoDeCuentaNavistarPagosResult) {
            this.ObtenEstadoDeCuentaNavistarPagosResult = ObtenEstadoDeCuentaNavistarPagosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuenta", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequestBody Body;
        
        public ObtenEstadoDeCuentaRequest() {
        }
        
        public ObtenEstadoDeCuentaRequest(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int claveEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fechaInicioMovimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fechaFinalMovimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fechaInicioVencimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fechaFinalVencimientos;
        
        public ObtenEstadoDeCuentaRequestBody() {
        }
        
        public ObtenEstadoDeCuentaRequestBody(string usuario, string clave, int claveEmpresa, string contrato, string fechaInicioMovimientos, string fechaFinalMovimientos, string fechaInicioVencimientos, string fechaFinalVencimientos) {
            this.usuario = usuario;
            this.clave = clave;
            this.claveEmpresa = claveEmpresa;
            this.contrato = contrato;
            this.fechaInicioMovimientos = fechaInicioMovimientos;
            this.fechaFinalMovimientos = fechaFinalMovimientos;
            this.fechaInicioVencimientos = fechaInicioVencimientos;
            this.fechaFinalVencimientos = fechaFinalVencimientos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponseBody Body;
        
        public ObtenEstadoDeCuentaResponse() {
        }
        
        public ObtenEstadoDeCuentaResponse(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenEstadoDeCuentaResult;
        
        public ObtenEstadoDeCuentaResponseBody() {
        }
        
        public ObtenEstadoDeCuentaResponseBody(string ObtenEstadoDeCuentaResult) {
            this.ObtenEstadoDeCuentaResult = ObtenEstadoDeCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEstadoDeCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEstadoDeCuenta", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequestBody Body;
        
        public EnviaEstadoDeCuentaRequest() {
        }
        
        public EnviaEstadoDeCuentaRequest(NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEstadoDeCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int claveEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contratos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fechaInicioMovimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime fechaFinalMovimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime fechaInicioVencimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime fechaFinalVencimientos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string correoEnvio;
        
        public EnviaEstadoDeCuentaRequestBody() {
        }
        
        public EnviaEstadoDeCuentaRequestBody(string usuario, string clave, int claveEmpresa, string contratos, System.DateTime fechaInicioMovimientos, System.DateTime fechaFinalMovimientos, System.DateTime fechaInicioVencimientos, System.DateTime fechaFinalVencimientos, string correoEnvio) {
            this.usuario = usuario;
            this.clave = clave;
            this.claveEmpresa = claveEmpresa;
            this.contratos = contratos;
            this.fechaInicioMovimientos = fechaInicioMovimientos;
            this.fechaFinalMovimientos = fechaFinalMovimientos;
            this.fechaInicioVencimientos = fechaInicioVencimientos;
            this.fechaFinalVencimientos = fechaFinalVencimientos;
            this.correoEnvio = correoEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEstadoDeCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEstadoDeCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponseBody Body;
        
        public EnviaEstadoDeCuentaResponse() {
        }
        
        public EnviaEstadoDeCuentaResponse(NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEstadoDeCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaEstadoDeCuentaResult;
        
        public EnviaEstadoDeCuentaResponseBody() {
        }
        
        public EnviaEstadoDeCuentaResponseBody(string EnviaEstadoDeCuentaResult) {
            this.EnviaEstadoDeCuentaResult = EnviaEstadoDeCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaInternoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuentaInterno", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequestBody Body;
        
        public ObtenEstadoDeCuentaInternoRequest() {
        }
        
        public ObtenEstadoDeCuentaInternoRequest(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaInternoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int claveEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string urlAcceso;
        
        public ObtenEstadoDeCuentaInternoRequestBody() {
        }
        
        public ObtenEstadoDeCuentaInternoRequestBody(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso) {
            this.usuario = usuario;
            this.clave = clave;
            this.claveEmpresa = claveEmpresa;
            this.contrato = contrato;
            this.urlAcceso = urlAcceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaInternoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuentaInternoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponseBody Body;
        
        public ObtenEstadoDeCuentaInternoResponse() {
        }
        
        public ObtenEstadoDeCuentaInternoResponse(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaInternoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavistarPagos.EstadoCuentaWs.Respuesta ObtenEstadoDeCuentaInternoResult;
        
        public ObtenEstadoDeCuentaInternoResponseBody() {
        }
        
        public ObtenEstadoDeCuentaInternoResponseBody(NavistarPagos.EstadoCuentaWs.Respuesta ObtenEstadoDeCuentaInternoResult) {
            this.ObtenEstadoDeCuentaInternoResult = ObtenEstadoDeCuentaInternoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaInternoNavistarPagosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuentaInternoNavistarPagos", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequestBody Body;
        
        public ObtenEstadoDeCuentaInternoNavistarPagosRequest() {
        }
        
        public ObtenEstadoDeCuentaInternoNavistarPagosRequest(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaInternoNavistarPagosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int claveEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string urlAcceso;
        
        public ObtenEstadoDeCuentaInternoNavistarPagosRequestBody() {
        }
        
        public ObtenEstadoDeCuentaInternoNavistarPagosRequestBody(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso) {
            this.usuario = usuario;
            this.clave = clave;
            this.claveEmpresa = claveEmpresa;
            this.contrato = contrato;
            this.urlAcceso = urlAcceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenEstadoDeCuentaInternoNavistarPagosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenEstadoDeCuentaInternoNavistarPagosResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponseBody Body;
        
        public ObtenEstadoDeCuentaInternoNavistarPagosResponse() {
        }
        
        public ObtenEstadoDeCuentaInternoNavistarPagosResponse(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenEstadoDeCuentaInternoNavistarPagosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavistarPagos.EstadoCuentaWs.Respuesta ObtenEstadoDeCuentaInternoNavistarPagosResult;
        
        public ObtenEstadoDeCuentaInternoNavistarPagosResponseBody() {
        }
        
        public ObtenEstadoDeCuentaInternoNavistarPagosResponseBody(NavistarPagos.EstadoCuentaWs.Respuesta ObtenEstadoDeCuentaInternoNavistarPagosResult) {
            this.ObtenEstadoDeCuentaInternoNavistarPagosResult = ObtenEstadoDeCuentaInternoNavistarPagosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioEstadoDeCuentaInternoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioEstadoDeCuentaInterno", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequestBody Body;
        
        public EnvioEstadoDeCuentaInternoRequest() {
        }
        
        public EnvioEstadoDeCuentaInternoRequest(NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnvioEstadoDeCuentaInternoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int claveEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string urlAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime fInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime fFinal;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime fVencimientosDe;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime fVencimientosA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string correo;
        
        public EnvioEstadoDeCuentaInternoRequestBody() {
        }
        
        public EnvioEstadoDeCuentaInternoRequestBody(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso, System.DateTime fInicio, System.DateTime fFinal, System.DateTime fVencimientosDe, System.DateTime fVencimientosA, string correo) {
            this.usuario = usuario;
            this.clave = clave;
            this.claveEmpresa = claveEmpresa;
            this.contrato = contrato;
            this.urlAcceso = urlAcceso;
            this.fInicio = fInicio;
            this.fFinal = fFinal;
            this.fVencimientosDe = fVencimientosDe;
            this.fVencimientosA = fVencimientosA;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioEstadoDeCuentaInternoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioEstadoDeCuentaInternoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponseBody Body;
        
        public EnvioEstadoDeCuentaInternoResponse() {
        }
        
        public EnvioEstadoDeCuentaInternoResponse(NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnvioEstadoDeCuentaInternoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavistarPagos.EstadoCuentaWs.Respuesta EnvioEstadoDeCuentaInternoResult;
        
        public EnvioEstadoDeCuentaInternoResponseBody() {
        }
        
        public EnvioEstadoDeCuentaInternoResponseBody(NavistarPagos.EstadoCuentaWs.Respuesta EnvioEstadoDeCuentaInternoResult) {
            this.EnvioEstadoDeCuentaInternoResult = EnvioEstadoDeCuentaInternoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSEstadosDeCuentaSoapChannel : NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEstadosDeCuentaSoapClient : System.ServiceModel.ClientBase<NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap>, NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap {
        
        public WSEstadosDeCuentaSoapClient() {
        }
        
        public WSEstadosDeCuentaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEstadosDeCuentaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEstadosDeCuentaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEstadosDeCuentaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponse NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuentaNavistarPagos(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest request) {
            return base.Channel.ObtenEstadoDeCuentaNavistarPagos(request);
        }
        
        public NavistarPagos.EstadoCuentaWs.ArrayOfString ObtenEstadoDeCuentaNavistarPagos(string usuario, string clave, int claveEmpresa, string contrato, string fechaInicioMovimientos, string fechaFinalMovimientos, string fechaInicioVencimientos, string fechaFinalVencimientos) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.fechaInicioMovimientos = fechaInicioMovimientos;
            inValue.Body.fechaFinalMovimientos = fechaFinalMovimientos;
            inValue.Body.fechaInicioVencimientos = fechaInicioVencimientos;
            inValue.Body.fechaFinalVencimientos = fechaFinalVencimientos;
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponse retVal = ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuentaNavistarPagos(inValue);
            return retVal.Body.ObtenEstadoDeCuentaNavistarPagosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponse> NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuentaNavistarPagosAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest request) {
            return base.Channel.ObtenEstadoDeCuentaNavistarPagosAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosResponse> ObtenEstadoDeCuentaNavistarPagosAsync(string usuario, string clave, int claveEmpresa, string contrato, string fechaInicioMovimientos, string fechaFinalMovimientos, string fechaInicioVencimientos, string fechaFinalVencimientos) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaNavistarPagosRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.fechaInicioMovimientos = fechaInicioMovimientos;
            inValue.Body.fechaFinalMovimientos = fechaFinalMovimientos;
            inValue.Body.fechaInicioVencimientos = fechaInicioVencimientos;
            inValue.Body.fechaFinalVencimientos = fechaFinalVencimientos;
            return ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuentaNavistarPagosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponse NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuenta(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest request) {
            return base.Channel.ObtenEstadoDeCuenta(request);
        }
        
        public string ObtenEstadoDeCuenta(string usuario, string clave, int claveEmpresa, string contrato, string fechaInicioMovimientos, string fechaFinalMovimientos, string fechaInicioVencimientos, string fechaFinalVencimientos) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.fechaInicioMovimientos = fechaInicioMovimientos;
            inValue.Body.fechaFinalMovimientos = fechaFinalMovimientos;
            inValue.Body.fechaInicioVencimientos = fechaInicioVencimientos;
            inValue.Body.fechaFinalVencimientos = fechaFinalVencimientos;
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponse retVal = ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuenta(inValue);
            return retVal.Body.ObtenEstadoDeCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponse> NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuentaAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest request) {
            return base.Channel.ObtenEstadoDeCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaResponse> ObtenEstadoDeCuentaAsync(string usuario, string clave, int claveEmpresa, string contrato, string fechaInicioMovimientos, string fechaFinalMovimientos, string fechaInicioVencimientos, string fechaFinalVencimientos) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.fechaInicioMovimientos = fechaInicioMovimientos;
            inValue.Body.fechaFinalMovimientos = fechaFinalMovimientos;
            inValue.Body.fechaInicioVencimientos = fechaInicioVencimientos;
            inValue.Body.fechaFinalVencimientos = fechaFinalVencimientos;
            return ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponse NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.EnviaEstadoDeCuenta(NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest request) {
            return base.Channel.EnviaEstadoDeCuenta(request);
        }
        
        public string EnviaEstadoDeCuenta(string usuario, string clave, int claveEmpresa, string contratos, System.DateTime fechaInicioMovimientos, System.DateTime fechaFinalMovimientos, System.DateTime fechaInicioVencimientos, System.DateTime fechaFinalVencimientos, string correoEnvio) {
            NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest inValue = new NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contratos = contratos;
            inValue.Body.fechaInicioMovimientos = fechaInicioMovimientos;
            inValue.Body.fechaFinalMovimientos = fechaFinalMovimientos;
            inValue.Body.fechaInicioVencimientos = fechaInicioVencimientos;
            inValue.Body.fechaFinalVencimientos = fechaFinalVencimientos;
            inValue.Body.correoEnvio = correoEnvio;
            NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponse retVal = ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).EnviaEstadoDeCuenta(inValue);
            return retVal.Body.EnviaEstadoDeCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponse> NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.EnviaEstadoDeCuentaAsync(NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest request) {
            return base.Channel.EnviaEstadoDeCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaResponse> EnviaEstadoDeCuentaAsync(string usuario, string clave, int claveEmpresa, string contratos, System.DateTime fechaInicioMovimientos, System.DateTime fechaFinalMovimientos, System.DateTime fechaInicioVencimientos, System.DateTime fechaFinalVencimientos, string correoEnvio) {
            NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest inValue = new NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.EnviaEstadoDeCuentaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contratos = contratos;
            inValue.Body.fechaInicioMovimientos = fechaInicioMovimientos;
            inValue.Body.fechaFinalMovimientos = fechaFinalMovimientos;
            inValue.Body.fechaInicioVencimientos = fechaInicioVencimientos;
            inValue.Body.fechaFinalVencimientos = fechaFinalVencimientos;
            inValue.Body.correoEnvio = correoEnvio;
            return ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).EnviaEstadoDeCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponse NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuentaInterno(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest request) {
            return base.Channel.ObtenEstadoDeCuentaInterno(request);
        }
        
        public NavistarPagos.EstadoCuentaWs.Respuesta ObtenEstadoDeCuentaInterno(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.urlAcceso = urlAcceso;
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponse retVal = ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuentaInterno(inValue);
            return retVal.Body.ObtenEstadoDeCuentaInternoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponse> NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuentaInternoAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest request) {
            return base.Channel.ObtenEstadoDeCuentaInternoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoResponse> ObtenEstadoDeCuentaInternoAsync(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.urlAcceso = urlAcceso;
            return ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuentaInternoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponse NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuentaInternoNavistarPagos(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest request) {
            return base.Channel.ObtenEstadoDeCuentaInternoNavistarPagos(request);
        }
        
        public NavistarPagos.EstadoCuentaWs.Respuesta ObtenEstadoDeCuentaInternoNavistarPagos(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.urlAcceso = urlAcceso;
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponse retVal = ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuentaInternoNavistarPagos(inValue);
            return retVal.Body.ObtenEstadoDeCuentaInternoNavistarPagosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponse> NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.ObtenEstadoDeCuentaInternoNavistarPagosAsync(NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest request) {
            return base.Channel.ObtenEstadoDeCuentaInternoNavistarPagosAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosResponse> ObtenEstadoDeCuentaInternoNavistarPagosAsync(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso) {
            NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest inValue = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.ObtenEstadoDeCuentaInternoNavistarPagosRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.urlAcceso = urlAcceso;
            return ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).ObtenEstadoDeCuentaInternoNavistarPagosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponse NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.EnvioEstadoDeCuentaInterno(NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest request) {
            return base.Channel.EnvioEstadoDeCuentaInterno(request);
        }
        
        public NavistarPagos.EstadoCuentaWs.Respuesta EnvioEstadoDeCuentaInterno(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso, System.DateTime fInicio, System.DateTime fFinal, System.DateTime fVencimientosDe, System.DateTime fVencimientosA, string correo) {
            NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest inValue = new NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.urlAcceso = urlAcceso;
            inValue.Body.fInicio = fInicio;
            inValue.Body.fFinal = fFinal;
            inValue.Body.fVencimientosDe = fVencimientosDe;
            inValue.Body.fVencimientosA = fVencimientosA;
            inValue.Body.correo = correo;
            NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponse retVal = ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).EnvioEstadoDeCuentaInterno(inValue);
            return retVal.Body.EnvioEstadoDeCuentaInternoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponse> NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap.EnvioEstadoDeCuentaInternoAsync(NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest request) {
            return base.Channel.EnvioEstadoDeCuentaInternoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoResponse> EnvioEstadoDeCuentaInternoAsync(string usuario, string clave, int claveEmpresa, string contrato, string urlAcceso, System.DateTime fInicio, System.DateTime fFinal, System.DateTime fVencimientosDe, System.DateTime fVencimientosA, string correo) {
            NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest inValue = new NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequest();
            inValue.Body = new NavistarPagos.EstadoCuentaWs.EnvioEstadoDeCuentaInternoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.claveEmpresa = claveEmpresa;
            inValue.Body.contrato = contrato;
            inValue.Body.urlAcceso = urlAcceso;
            inValue.Body.fInicio = fInicio;
            inValue.Body.fFinal = fFinal;
            inValue.Body.fVencimientosDe = fVencimientosDe;
            inValue.Body.fVencimientosA = fVencimientosA;
            inValue.Body.correo = correo;
            return ((NavistarPagos.EstadoCuentaWs.WSEstadosDeCuentaSoap)(this)).EnvioEstadoDeCuentaInternoAsync(inValue);
        }
    }
}
